In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 2

@author: yaning
"""
import numpy as np
import pickle

path = "/home/yaning/Documents/Spiking_NN/with_learning/"
np.set_printoptions(threshold=np.inf)

In [27]:
dataset = np.array([
    [0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 1, 1],
    [0, 0, 0, 1, 0, 1],
    [0, 0, 0, 1, 1, 0],
    [0, 0, 1, 0, 0, 1],
    [0, 0, 1, 0, 1, 0],
    [0, 0, 1, 1, 0, 0],
    [0, 0, 1, 1, 1, 1],
    [0, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0],
    [0, 1, 0, 1, 0, 0],
    [0, 1, 0, 1, 1, 1],
    [0, 1, 1, 0, 0, 0],
    [0, 1, 1, 0, 1, 1],
    [0, 1, 1, 1, 0, 1],
    [0, 1, 1, 1, 1, 0],
    [1, 0, 0, 0, 0, 1],
    [1, 0, 0, 0, 1, 0],
    [1, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 1, 1],
    [1, 0, 1, 0, 0, 0],
    [1, 0, 1, 0, 1, 1],
    [1, 0, 1, 1, 0, 1],
    [1, 0, 1, 1, 1, 0],
    [1, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 1, 1],
    [1, 1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1, 0],
    [1, 1, 1, 0, 0, 1],
    [1, 1, 1, 0, 1, 0],
    [1, 1, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 1]
])

In [16]:
dataset[25]

array([1, 1, 0, 0, 1, 1])

In [5]:
dataset.shape

(32, 6)

In [20]:
dataset = [
    [0, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 1],
    [0, 1, 1, 0],
    [1, 0, 0, 1],
    [1, 0, 1, 0],
    [1, 1, 0, 0],
    [1, 1, 1, 1]
]

dataset = np.array(dataset)

In [33]:
# add
dataset = [
    # [0, 0, 0, 0],
    [0, 0, 1, 1],
    [0, 1, 0, 1],
    [0, 1, 1, 2],
    [1, 0, 0, 1],
    [1, 0, 1, 2],
    [1, 1, 0, 2],
    [1, 1, 1, 3]
]

dataset = np.array(dataset)

In [39]:
# black and white
dataset = [
    [1, 1],
    [0, 0],
    [1, 1],
    [1, 1],
    [0, 0],
    [1, 1],
    [1, 1],
    [0, 0]
]

dataset = np.array(dataset)

In [18]:
dataset.shape

(8, 2)

In [40]:
# form an shape (5000, 3) array with 5000 time points and 3 input neurons
# every fire is 45-50 cycles, 
pointCount = 6000
start_tstep = 500
one_cycle = np.concatenate((np.ones(45, dtype=bool), np.zeros(189, dtype=bool)))
all_cycles = np.tile(one_cycle, 23)

non_fire_array = np.zeros(pointCount, dtype=bool)
fire_array = non_fire_array.copy()
fire_array[start_tstep:all_cycles.shape[0]+start_tstep] = all_cycles


In [53]:
test = []
test.append([1,2,3])

In [54]:
test

[[1, 2, 3]]

In [41]:
firing_squence = []
# every cycle of this for loop is another firing pattern
for i in dataset:
    
    input_one = i[0]
    # input_two = i[1]
    # input_three = i[2]
    # input_four = i[3]
    # input_five = i[4]
    
    output_num = i[1]
    
    params = [input_one #, input_two, input_three, #input_four, input_five
              ]
    # params = [input_one, input_two, input_three]
    
    input_firing = []
    for param in params:
        if param == 0:
            input_firing.append(non_fire_array)
        else:
            input_firing.append(fire_array)
    
    # if the output number is zero then neuron_output_0 fires
    if output_num == 0:
        input_firing.append(fire_array)
        input_firing.append(non_fire_array)
        
    else:
        input_firing.append(non_fire_array)
        input_firing.append(fire_array)
        
    firing_squence.append(input_firing)
    

    
#     # age is input0; bmi is input1; stress is input2
#     age_f = age_choice[i]
#     bmi_f = bmi_choice[i]
#     stress_f = stress_choice[i]
    
#     frequencies = [age_f, bmi_f, stress_f]
#     print(frequencies)
#     fire = []
#     for f in frequencies:
#         # print(f)
#         replacement = np.tile(one_cycle, f+20)
#         # print(replacement)
#         temp = np.full(pointCount, False)
#         temp[start_tstep:replacement.shape[0]+start_tstep] = replacement
#         # print(temp[2000:3000])
#         fire.append(temp)
#     dataset.append(fire)

# dataset = np.array(dataset)

In [42]:
firing_squence = np.array(firing_squence)

In [43]:
firing_squence.shape

(8, 3, 6000)

In [62]:
firing_squence[-2,4]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [44]:
with open(path + "XOR_dataset_black_white.pkl", "wb") as f:
    pickle.dump((firing_squence, dataset), f)

In [9]:
dataset

array([[0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])