In [1]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 2

@author: yaning
"""

import numpy as np
np.random.seed(42)
np.set_printoptions(threshold=np.inf)

In [50]:
pointCount = 6500
num_frequency = 5
num_sample = 10

age_base = np.linspace(18, 80, num_frequency)
bmi_base = np.linspace(18, 40, num_frequency)
stress_base = np.linspace(1, 10, num_frequency)

five = np.arange(5)
age_choice = np.random.choice(five, num_sample)
bmi_choice = np.random.choice(five, num_sample)
stress_choice = np.random.choice(five, num_sample)

age = age_base[age_choice]
bmi = bmi_base[age_choice]
stress = stress_base[age_choice]


In [51]:
time_to_disease = (
    0.05 * age + 0.2 * bmi + 0.3 * stress + np.random.normal(0, 2, num_sample)
)

In [52]:
time_to_disease

array([11.0433124 , 10.72075869,  8.64105008, 16.19544093, 20.11897606,
        8.13846604, 10.14443833,  8.86912868,  8.6994923 , 16.89487964])

In [53]:
test=[False, False, False]
test[1:2] = [True]
test

[False, True, False]

In [60]:
# form an shape (5000, 3) array with 5000 time points and 3 input neurons
# every fire is 45-50 cycles, 
start_tstep = 500
one_cycle = np.concatenate((np.ones(45, dtype=bool), np.zeros(189, dtype=bool)))

dataset = []
# every cycle of this for loop is another dataset
for i in range(num_sample):
    # age is input0; bmi is input1; stress is input2
    age_f = age_choice[i]
    bmi_f = bmi_choice[i]
    stress_f = stress_choice[i]
    
    frequencies = [age_f, bmi_f, stress_f]
    print(frequencies)
    fire = []
    for f in frequencies:
        # print(f)
        replacement = np.tile(one_cycle, f+20)
        # print(replacement)
        temp = np.full(pointCount, False)
        temp[start_tstep:replacement.shape[0]+start_tstep] = replacement
        # print(temp[2000:3000])
        fire.append(temp)
    dataset.append(fire)

dataset = np.array(dataset)

[3, 3, 1]
[4, 2, 4]
[2, 4, 3]
[4, 1, 0]
[4, 3, 0]
[1, 1, 2]
[2, 3, 2]
[2, 4, 1]
[2, 0, 3]
[4, 3, 3]


In [55]:
dataset.shape

(10, 3, 6500)

In [56]:
dataset[1]

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
      

In [57]:
path = "/home/yaning/Documents/Spiking_NN/with_learning/"

np.save(path + 'dataset.npy', dataset)
np.save(path + 'output.npy', time_to_disease)

In [58]:
stress_choice[1]

4

In [59]:
dataset[1][:,2000:3000]

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
      